<?php
/**
 * Index.php
 *
 * @package myMVC
 * @copyright ueffing.net
 * @author Guido K.B.W. Üffing <info@ueffing.net>
 * @license GNU GENERAL PUBLIC LICENSE Version 3. See application/doc/COPYING
 */

/**
 * @name ${module}Policy
 */
namespace {module}\Policy;


/**
 * Index
 */
class Index
{
    /**
     * @return void
     * @throws \ReflectionException
     */
    public static function requestMethodHasToMatchRouteMethod ()
    {
        if (\MVC\Request::getCurrentRequest()->get_requestmethod() !== \MVC\Route::getCurrent()->get_method())
        {
            $oController = new \{module}\Controller\Index();
            $oController->notFound();
        }
    }
}
