<?php

/**
 * minify css/js files
 */
\MVC\Event::bind('mvc.reflex.reflect.targetObject.before', function(\MVC\DataType\DTArrayObject $oDTArrayObject) {
    \MVC\Minify::init();
});

/**
 * switch on InfoTool
 */
\MVC\Event::bind('mvc.reflex.reflect.targetObject.after', function (\MVC\DataType\DTArrayObject $oDTArrayObject) {
    if (true === \MVC\Config::get_MVC_INFOTOOL_ENABLE())
    {
        new \MVC\InfoTool(\{module}\View\Index::init());
    }
});

/**
 * Logging stops
 */
\MVC\Event::bind('mvc.debug.stop.after', function (\MVC\DataType\DTArrayObject $oDTArrayObject) {
    \MVC\Log::write("\n\n*** STOP ***\n" . print_r($oDTArrayObject->get_akeyvalue()[0]->get_sValue(), true));
});

/**
 * enable Session
 */
\MVC\Event::bind('mvc.application.setSession.before', function(\MVC\DataType\DTArrayObject $oDTArrayObject) {
    \{module}\Event\Index::enableSession($oDTArrayObject);
});
