<?php

#-------------------------------------------------------------
# declare bindings

$aEvent = [
    'mvc.reflex.reflect.targetObject.before' => array(
        function(\MVC\DataType\DTArrayObject $oDTArrayObject) { // minify css/js files
            \MVC\Minify::init();
        }
    ),
    'mvc.reflex.reflect.targetObject.after' => array(
        function (\MVC\DataType\DTArrayObject $oDTArrayObject) { // switch on InfoTool
            if (true === \MVC\Config::get_MVC_INFOTOOL_ENABLE())
            {
                new \MVC\InfoTool(\{module}\View\Index::init());
            }
        }
    ),
    'mvc.debug.stop.after' => array(
        function (\MVC\DataType\DTArrayObject $oDTArrayObject) { // Logging stops
            \MVC\Log::write("\n\n*** STOP ***\n" . print_r($oDTArrayObject->get_akeyvalue()[0]->get_sValue(), true));
        }
    ),
    'mvc.application.setSession.before' => array(
        function(\MVC\DataType\DTArrayObject $oDTArrayObject) { // enable Session
            \{module}\Event\Index::enableSession($oDTArrayObject);
        }
    ),
];

#-------------------------------------------------------------
# process: bind the declared ones

\MVC\Event::processBindConfigStack($aEvent);