<?php

/*
 * you can use your own $oDTRoutingAdditional
 * @see modules/{module}/etc/config/{module}/config/_dataType.php
 */

$oDTRoutingAdditional = \MVC\DataType\DTRoutingAdditional::create()
    ->set_sTitle('{module}')
    ->set_sLayout('Frontend/layout/index.tpl')
    ->set_sMainmenu('Frontend/layout/menu.tpl')
    ->set_sContent('Frontend/content/index.tpl')
    ->set_sHeader('Frontend/layout/header.tpl')
    ->set_sNoscript('Frontend/content/_noscript.tpl')
    ->set_sCookieConsent('Frontend/content/_cookieConsent.tpl')
    ->set_sFooter('Frontend/layout/footer.tpl')
    ->set_aStyle(array (
        '/myMVC/assets/bootstrap-5.3.2-dist/css/bootstrap.min.css',
        '/myMVC/assets/fontawesome-free-6.4.2-web/css/all.min.css',
        '/myMVC/styles/myMVC.min.css',
    ))
    ->set_aScript(array (
        '/myMVC/assets/jquery-3.7.1/jquery-3.7.1.min.js',
        '/myMVC/assets/jquery-cookie-1.4.1/jquery.cookie.min.js',
        '/myMVC/assets/bootstrap-5.3.2-dist/js/bootstrap.min.js',
        '/myMVC/scripts/cookieConsent.min.js',
    ));

/*
 * Routes
 */
\MVC\Route::mix(
    ['GET', 'POST'],
    '/',
    '\{module}\Controller\Index::index',
    $oDTRoutingAdditional->getPropertyJson()
);
\MVC\Route::get(
    '/404/',
    '\{module}\Controller\Index::notFound',
    $oDTRoutingAdditional->set_sTitle('404')
        ->set_sContent('Frontend/content/404.tpl')
        ->getPropertyJson()
);
