<?php

# List of myMVC Standard Events
# @see https://mymvc.ueffing.net/3.4.x/events#myMVCStandardEvents


\MVC\Event::processBindConfigStack([

    /**
     * after current request was get
     */
    'mvc.request.getCurrentRequest.after' => [
        /*
         * logging requests
         */
        function(\MVC\DataType\DTArrayObject $oDTArrayObject, \MVC\DataType\DTEventContext $oDTEventContext) {

            if (false === \MVC\Config::get_MVC_LOG_REQUEST())
            {
                return false;
            }

            /** @var \MVC\DataType\DTRequestCurrent $oDTRequestCurrent */
            $oDTRequestCurrent = $oDTArrayObject->flatten()['oDTRequestCurrent'];

            \MVC\Log::write($oDTRequestCurrent, \MVC\Config::get_MVC_LOG_FILE_REQUEST());
        },
    ],

]);
