<?php
/**
 * Index.php
 *
 * @package myMVC
 * @copyright ueffing.net
 * @author Guido K.B.W. Üffing <mymvc@ueffing.net>
 * @license GNU GENERAL PUBLIC LICENSE Version 3. See application/doc/COPYING
 */

/**
 * @name ${module}Controller
 */
namespace {module}\Controller;

use App\Controller;
use MVC\DataType\DTRequestCurrent;
use MVC\DataType\DTRoute;

/**
 * @extends Controller
 */
class Index extends Controller
{
    /**
     * @return void
     */
    public static function __preconstruct()
    {
        ;
    }

    /**
     * @param \MVC\DataType\DTRequestCurrent $oDTRequestCurrent
     * @param \MVC\DataType\DTRoute          $oDTRoute
     * @throws \ReflectionException
     */
    public function __construct(DTRequestCurrent $oDTRequestCurrent, DTRoute $oDTRoute)
	{
        \{module}\View\Index::init()->autoAssign($oDTRoute);
	}

    /**
     * @param \MVC\DataType\DTRequestCurrent $oDTRequestCurrent
     * @param \MVC\DataType\DTRoute          $oDTRoute
     * @return void
     * @throws \ReflectionException
     */
	public function index(DTRequestCurrent $oDTRequestCurrent, DTRoute $oDTRoute)
	{
		;
	}

    /**
     * @param \MVC\DataType\DTRequestCurrent $oDTRequestCurrent
     * @param \MVC\DataType\DTRoute          $oDTRoute
     * @return void
     * @throws \ReflectionException
     */
    public function notFound(DTRequestCurrent $oDTRequestCurrent, DTRoute $oDTRoute)
    {
        http_response_code(404);
    }

    /**
     * @throws \ReflectionException
     * @throws \SmartyException
     */
	public function __destruct()
	{
        \{module}\View\Index::init()->render();
	}
}