<?php

/**
 * @name ${module}DataType
 */
namespace {module}\DataType;

use MVC\MVCTrait\TraitDataType;

class DTRoutingAdditional
{
    use TraitDataType;

    public const DTHASH = 'd1146596bdc5be9f318fabe93f3bf5fb';

    /**
     * @required true
     * @var string
     */
    protected $sTitle;

    /**
     * @required true
     * @var string
     */
    protected $sLayout;

    /**
     * @required true
     * @var string
     */
    protected $sMainmenu;

    /**
     * @required true
     * @var string
     */
    protected $sContent;

    /**
     * @required true
     * @var string
     */
    protected $sHeader;

    /**
     * @required true
     * @var string
     */
    protected $sNoscript;

    /**
     * @required true
     * @var string
     */
    protected $sCookieConsent;

    /**
     * @required true
     * @var string
     */
    protected $sFooter;

    /**
     * @required true
     * @var array
     */
    protected $aStyle;

    /**
     * @required true
     * @var array
     */
    protected $aScript;

    /**
     * DTRoutingAdditional constructor.
     * @param array $aData
     * @throws \ReflectionException
     */
    public function __construct(array $aData = array())
    {
        \MVC\Event::RUN ('DTRoutingAdditional.__construct.before', $aData);

        $this->sTitle = '';
        $this->sLayout = '';
        $this->sMainmenu = '';
        $this->sContent = '';
        $this->sHeader = '';
        $this->sNoscript = '';
        $this->sCookieConsent = '';
        $this->sFooter = '';
        $this->aStyle = array();
        $this->aScript = array();

        foreach ($aData as $sKey => $mValue)
        {
            $sMethod = 'set_' . $sKey;

            if (method_exists($this, $sMethod))
            {
                $this->$sMethod($mValue);
            }
        }

        \MVC\Event::RUN ('DTRoutingAdditional.__construct.after', $aData);
    }

    /**
     * @param array $aData
     * @return DTRoutingAdditional
     * @throws \ReflectionException
     */
    public static function create(array $aData = array())
    {
        \MVC\Event::RUN ('DTRoutingAdditional.create.before', $aData);

        $oObject = new self($aData);

        \MVC\Event::RUN ('DTRoutingAdditional.create.after', $aData);

        return $oObject;
    }

    /**
     * @param string $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_sTitle(string $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_sTitle.before', $mValue);

        $this->sTitle = (string) $mValue;

        return $this;
    }

    /**
     * @param string $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_sLayout(string $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_sLayout.before', $mValue);

        $this->sLayout = (string) $mValue;

        return $this;
    }

    /**
     * @param string $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_sMainmenu(string $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_sMainmenu.before', $mValue);

        $this->sMainmenu = (string) $mValue;

        return $this;
    }

    /**
     * @param string $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_sContent(string $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_sContent.before', $mValue);

        $this->sContent = (string) $mValue;

        return $this;
    }

    /**
     * @param string $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_sHeader(string $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_sHeader.before', $mValue);

        $this->sHeader = (string) $mValue;

        return $this;
    }

    /**
     * @param string $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_sNoscript(string $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_sNoscript.before', $mValue);

        $this->sNoscript = (string) $mValue;

        return $this;
    }

    /**
     * @param string $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_sCookieConsent(string $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_sCookieConsent.before', $mValue);

        $this->sCookieConsent = (string) $mValue;

        return $this;
    }

    /**
     * @param string $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_sFooter(string $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_sFooter.before', $mValue);

        $this->sFooter = (string) $mValue;

        return $this;
    }

    /**
     * @param array $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_aStyle(array $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_aStyle.before', $mValue);

        $this->aStyle = (array) $mValue;

        return $this;
    }

    /**
     * @param array $mValue
     * @return $this
     * @throws \ReflectionException
     */
    public function set_aScript(array $mValue)
    {
        \MVC\Event::RUN ('DTRoutingAdditional.set_aScript.before', $mValue);

        $this->aScript = (array) $mValue;

        return $this;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    public function get_sTitle() : string
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_sTitle.before', $this->sTitle);

        return $this->sTitle;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    public function get_sLayout() : string
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_sLayout.before', $this->sLayout);

        return $this->sLayout;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    public function get_sMainmenu() : string
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_sMainmenu.before', $this->sMainmenu);

        return $this->sMainmenu;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    public function get_sContent() : string
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_sContent.before', $this->sContent);

        return $this->sContent;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    public function get_sHeader() : string
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_sHeader.before', $this->sHeader);

        return $this->sHeader;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    public function get_sNoscript() : string
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_sNoscript.before', $this->sNoscript);

        return $this->sNoscript;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    public function get_sCookieConsent() : string
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_sCookieConsent.before', $this->sCookieConsent);

        return $this->sCookieConsent;
    }

    /**
     * @return string
     * @throws \ReflectionException
     */
    public function get_sFooter() : string
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_sFooter.before', $this->sFooter);

        return $this->sFooter;
    }

    /**
     * @return array
     * @throws \ReflectionException
     */
    public function get_aStyle() : array
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_aStyle.before', $this->aStyle);

        return $this->aStyle;
    }

    /**
     * @return array
     * @throws \ReflectionException
     */
    public function get_aScript() : array
    {
        \MVC\Event::RUN ('DTRoutingAdditional.get_aScript.before', $this->aScript);

        return $this->aScript;
    }

    /**
     * @return string
     */
    public static function getPropertyName_sTitle()
    {
        return 'sTitle';
    }

    /**
     * @return string
     */
    public static function getPropertyName_sLayout()
    {
        return 'sLayout';
    }

    /**
     * @return string
     */
    public static function getPropertyName_sMainmenu()
    {
        return 'sMainmenu';
    }

    /**
     * @return string
     */
    public static function getPropertyName_sContent()
    {
        return 'sContent';
    }

    /**
     * @return string
     */
    public static function getPropertyName_sHeader()
    {
        return 'sHeader';
    }

    /**
     * @return string
     */
    public static function getPropertyName_sNoscript()
    {
        return 'sNoscript';
    }

    /**
     * @return string
     */
    public static function getPropertyName_sCookieConsent()
    {
        return 'sCookieConsent';
    }

    /**
     * @return string
     */
    public static function getPropertyName_sFooter()
    {
        return 'sFooter';
    }

    /**
     * @return string
     */
    public static function getPropertyName_aStyle()
    {
        return 'aStyle';
    }

    /**
     * @return string
     */
    public static function getPropertyName_aScript()
    {
        return 'aScript';
    }

    /**
     * @return false|string JSON
     */
    public function __toString()
    {
        return $this->getPropertyJson();
    }

    /**
     * @return false|string
     */
    public function getPropertyJson()
    {
        return json_encode($this->getPropertyArray());
    }

    /**
     * @return array
     */
    public function getPropertyArray()
    {
        return get_object_vars($this);
    }

    /**
     * @return array
     * @throws \ReflectionException
     */
    public function getConstantArray()
    {
        $oReflectionClass = new \ReflectionClass($this);
        $aConstant = $oReflectionClass->getConstants();

        return $aConstant;
    }

    /**
     * @return $this
     */
    public function flushProperties()
    {
        foreach ($this->getPropertyArray() as $sKey => $mValue)
        {
            $sMethod = 'set_' . $sKey;

            if (method_exists($this, $sMethod))
            {
                $this->$sMethod('');
            }
        }

        return $this;
    }
}
