<?php

namespace {module}\Model\Table;

use MVC\DB\DataType\DB\Foreign;
use MVC\DB\Model\Db;

class User extends Db
{
    /**
     * @var array
     */
    protected $aField = array();

    /**
     * @param array $aDbConfig
     * @throws \ReflectionException
     */
    public function __construct(array $aDbConfig = array())
    {
        /*
         * ALTER TABLE `FooModelTableUser` ADD UNIQUE(`email`)
         */
        $this->aField = array(
            'email'     => 'varchar(255)    COLLATE utf8_general_ci NOT NULL UNIQUE',
            'active'    => "int(1)          DEFAULT '0'             NOT NULL",
            'uuid'      => "varchar(36)     COLLATE utf8_general_ci NOT NULL UNIQUE COMMENT 'uuid permanent'",
            'uuidtmp'   => "varchar(36)     COLLATE utf8_general_ci NOT NULL UNIQUE COMMENT 'uuid; changes on create|login'",
            'password'  => 'varchar(60)     COLLATE utf8_general_ci NOT NULL',
            'nickname'  => "varchar(10)     COLLATE utf8_general_ci NOT NULL",
            'forename'  => "varchar(25)     COLLATE utf8_general_ci NOT NULL",
            'lastname'  => "varchar(25)     COLLATE utf8_general_ci NOT NULL",
        );

        // basic creation of the table
        parent::__construct(
            $this->aField,
            $aDbConfig
        );
        $this->setForeignKey(
            Foreign::create()
                ->set_sForeignKey('id_TableGroup')
                ->set_sReferenceTable('{module}ModelTableGroup')
        );
    }
}





















