<?php
/**
 * Index.php
 *
 * @package myMVC
 * @copyright ueffing.net
 * @author Guido K.B.W. Üffing <info@ueffing.net>
 * @license GNU GENERAL PUBLIC LICENSE Version 3. See application/doc/COPYING
 */

/**
 * @name ${module}Event
 */
namespace {module}\Event;

use MVC\Config;
use MVC\DataType\DTArrayObject;
use MVC\Event;
use MVC\Registry;
use MVC\Request;

/**
 * Index
 */
class Index
{
	/**
	 * \{module}\Event\Index
	 * @var \{module}\Event\Index
	 */
	private static $_oInstance = NULL;

    /**
     * Index constructor.
     * @throws \ReflectionException
     */
    protected function __construct()
    {
        foreach (get(Registry::get('MODULE')['{module}']['EVENT_BIND'], array()) as $sEvent => $mData)
        {
            if (true === is_array($mData))
            {
                foreach ($mData as $oClosure)
                {
                    Event::bind($sEvent, $oClosure, null);
                }

                continue;
            }

            Event::bind($sEvent, $mData);
        }
    }

    /**
     * Singleton instance
     * @return \{module}\Event\Index
     * @throws \ReflectionException
     */
    public static function getInstance()
    {
        if (null === self::$_oInstance)
        {
            self::$_oInstance = new self ();
        }

        return self::$_oInstance;
    }

    /**
     * prevent any cloning
     * @return void
     */
    private function __clone()
    {
        ;
    }

    /**
     * activates Session
     * gets active by triggered event "mvc.application.setSession.before"
     * @see /modules/{module}/etc/config/{module}/config/{env}.php
     * @param DTArrayObject $oDTArrayObject
     * @throws \ReflectionException
     */
    public static function enableSession(\MVC\DataType\DTArrayObject $oDTArrayObject)
    {
        $aEnableSessionForController = get(Registry::get('MODULE')['{module}']['SESSION']['aEnableSessionForController'], array());
        $aDisableSessionForController = get(Registry::get('MODULE')['{module}']['SESSION']['aDisableSessionForController'], array());

        $bEnable = (
            // current controller
            in_array(Request::getControllerName(), $aEnableSessionForController)
            ||
            // any
            in_array('*', $aEnableSessionForController)
        );

        $bDisable = (
            // current controller
            in_array(Request::getControllerName(), $aDisableSessionForController)
            ||
            // any
            in_array('*', $aDisableSessionForController)
        );

        if (true == $bEnable
            && false == $bDisable
            && isset($_COOKIE['myMVC_cookieConsent'])
            && "true" == $_COOKIE['myMVC_cookieConsent']
        )
        {
            Config::set_MVC_SESSION_ENABLE();
        }
    }
	
	/**
	 * Destructor
	 * @return void
	 */
	public function __destruct()
	{
		;
	}
}
 
