<?php
/**
 * Index.php
 *
 * @package myMVC
 * @copyright ueffing.net
 * @author Guido K.B.W. Üffing <info@ueffing.net>
 * @license GNU GENERAL PUBLIC LICENSE Version 3.
 */

/**
 * @name ${module}Controller
 */
namespace {module}\Controller;

use MVC\Route;

/**
 * Index
 * @implements \MVC\MVCInterface\Controller
 */
class Index implements \MVC\MVCInterface\Controller
{
    /**
     * @return void
     */
    public static function __preconstruct ()
    {
        ;
    }
	
    /**
     * Index constructor.
     * @throws \ReflectionException
     * @throws \SmartyException
     */
	public function __construct ()
	{
        \{module}\View\Index::init()->autoAssign();
	}

    /**
     * @return void
     */
	public function index ()
	{
		;
	}

    /**
     * @return void
     */
    public function notFound()
    {
        http_response_code(404);
    }

    /**
     * @throws \ReflectionException
     * @throws \SmartyException
     */
	public function __destruct ()
	{
        \{module}\View\Index::init()->render();
	}
}