<?php
/**
 * Index.php
 *
 * @package myMVC
 * @copyright ueffing.net
 * @author Guido K.B.W. Üffing <info@ueffing.net>
 * @license GNU GENERAL PUBLIC LICENSE Version 3. See application/doc/COPYING
 */


/**
 * @name ${module}Controller
 */
namespace {module}\Controller;

/**
 * Index
 * @implements \MVC\MVCInterface\Controller
 */
class Index implements \MVC\MVCInterface\Controller
{
	/**
	 * Session Object
	 * @var \MVC\Session
	 */
	protected $_oMVCSession;
	
	/**
	 * routing array for current page
	 * @var array
	 */
	protected $_aRoutingCurrent = array();

	/**
	 * View Object
	 * @var \{module}\View\Index
	 */
	public $oView;

	/**
	 * Model Object
	 * @var \{module}\Model\Index
	 */
	protected $_oModel;

	/**
	 * this method is autom. called by MVC_Application->runTargetClassBeforeMethod()
	 * in very early stage
     * @return void
     */
	public static function __preconstruct ()
	{
		// start event listener
		\{module}\Event\Index::getInstance();
	}
	
    /**
     * Index constructor.
     * @throws \ReflectionException
     * @throws \SmartyException
     */
	public function __construct ()
	{
        \MVC\Request::handleFallback();
		$this->_oMVCSession = \MVC\Session::is();
		$this->_aRoutingCurrent = \MVC\Router::getRoutingCurrent();
		$this->_oModel = new \{module}\Model\Index();
		$this->oView = new \{module}\View\Index();
        $this->oView->autoAssign($this->_aRoutingCurrent);
	}

    /**
     * @return void
     */
	public function index ()
	{
		;
	}

    /**
     * @return void
     */
    public function notFound()
    {
        http_response_code(404);
    }

    /**
     * @throws \ReflectionException
     * @throws \SmartyException
     */
	public function __destruct ()
	{
		$this->oView->render ();
	}
}
