<?php

//-------------------------------------------------------------------------------------
// MVC

// enable debug output
$aConfig['MVC_DEBUG'] = false;

/**
 * Misc
 */
// override MVC's fallback routing
$aConfig['MVC_ROUTING_FALLBACK'] = $aConfig['MVC_GET_PARAM_MODULE'] . '={module}&'
    . $aConfig['MVC_GET_PARAM_C'] . '=index&'
    . $aConfig['MVC_GET_PARAM_M'] . '=index';

// module's config dir
$aConfig['MVC_MODULE_CURRENT_ETC_DIR'] = $aConfig['MVC_MODULES'] . '/{module}/etc';
$aConfig['MVC_MODULE_CURRENT_CONFIG_DIR'] = $aConfig['MVC_MODULES'] . '/{module}/etc/config';
$aConfig['MVC_MODULE_CURRENT_STAGING_CONFIG_DIR'] = $aConfig['MVC_MODULE_CURRENT_CONFIG_DIR'] . '/{module}/config';

// composer dir
$aConfig['MVC_MODULE_CURRENT_COMPOSER_DIR'] = realpath(__DIR__ . '/../') . '/config/{module}';

// Smarty
$aConfig['MVC_VIEW_TEMPLATES'] = $aConfig['MVC_MODULES'] . '/' . basename(realpath(__DIR__ . '/../../')) . '/templates';
$aConfig['MVC_SMARTY_TEMPLATE_DIR'] = $aConfig['MVC_VIEW_TEMPLATES'];
$aConfig['MVC_SMARTY_TEMPLATE_DEFAULT'] = 'Frontend/layout/index.tpl';

// Add Location of Smarty PlugIns
$aConfig['MVC_SMARTY_PLUGINS_DIR'][] = $aConfig['MVC_MODULES'] . '/' . basename(realpath(__DIR__ . '/../../')) . '/etc/smarty';
