<?php

$aConfig = array(
    'dir' => \MVC\Registry::get("MVC_MODULES") . '/DB/DataType/SQL/',
    'unlinkDir' => true,
    'class' => array(
        0 => array(
            'name' => 'FieldTypeConcrete',
            'namespace' => 'DB\\DataType\\SQL',
        ),
        1 => array(
            'name' => 'TypeChar',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        2 => array(
            'name' => 'TypeVarchar',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        3 => array(
            'name' => 'TypeBinary',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        4 => array(
            'name' => 'TypeVarbinary',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        5 => array(
            'name' => 'TypeTinyblob',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        6 => array(
            'name' => 'TypeBlob',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        7 => array(
            'name' => 'TypeMediumblob',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        8 => array(
            'name' => 'TypeLongblob',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        9 => array(
            'name' => 'TypeTinytext',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        10 => array(
            'name' => 'TypeText',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        11 => array(
            'name' => 'TypeMediumtext',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        12 => array(
            'name' => 'TypeLongtext',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        13 => array(
            'name' => 'TypeEnum',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        14 => array(
            'name' => 'TypeSet',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        15 => array(
            'name' => 'TypeDate',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        16 => array(
            'name' => 'TypeTime',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        17 => array(
            'name' => 'TypeDatetime',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        18 => array(
            'name' => 'TypeTimestamp',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        19 => array(
            'name' => 'TypeYear',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        20 => array(
            'name' => 'TypeTinyint',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        21 => array(
            'name' => 'TypeSmallint',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        22 => array(
            'name' => 'TypeMediumint',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        23 => array(
            'name' => 'TypeInt',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        24 => array(
            'name' => 'TypeBigint',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        25 => array(
            'name' => 'TypeFloat',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        26 => array(
            'name' => 'TypeDouble',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        27 => array(
            'name' => 'TypeBit',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        28 => array(
            'name' => 'TypeBoolean',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        29 => array(
            'name' => 'TypeBool',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        30 => array(
            'name' => 'TypeGeometry',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        31 => array(
            'name' => 'TypePoint',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        32 => array(
            'name' => 'TypeLinestring',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        33 => array(
            'name' => 'TypePolygon',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        34 => array(
            'name' => 'TypeGeometrycollection',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        35 => array(
            'name' => 'TypeMultilinestring',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        36 => array(
            'name' => 'TypeMultipoint',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        37 => array(
            'name' => 'TypeMultipolygon',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        38 => array(
            'name' => 'TypeJson',
            'namespace' => 'DB\\DataType\\SQL',
            'extends' => 'FieldTypeConcrete',
        ),
        39 => array(
            'name' => 'FieldType',
            'namespace' => 'DB\\DataType\\SQL',
            'property' => array(
                0 => array(
                    'key' => 'typeChar',
                    'var' => 'TypeChar',
                    'visibility' => 'public',
                    'value' => 'new TypeChar()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                1 => array(
                    'key' => 'typeVarchar',
                    'var' => 'TypeVarchar',
                    'visibility' => 'public',
                    'value' => 'new TypeVarchar()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                2 => array(
                    'key' => 'typeBinary',
                    'var' => 'TypeBinary',
                    'visibility' => 'public',
                    'value' => 'new TypeBinary()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                3 => array(
                    'key' => 'typeVarbinary',
                    'var' => 'TypeVarbinary',
                    'visibility' => 'public',
                    'value' => 'new TypeVarbinary()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                4 => array(
                    'key' => 'typeTinyblob',
                    'var' => 'TypeTinyblob',
                    'visibility' => 'public',
                    'value' => 'new TypeTinyblob()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                5 => array(
                    'key' => 'typeBlob',
                    'var' => 'TypeBlob',
                    'visibility' => 'public',
                    'value' => 'new TypeBlob()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                6 => array(
                    'key' => 'typeMediumblob',
                    'var' => 'TypeMediumblob',
                    'visibility' => 'public',
                    'value' => 'new TypeMediumblob()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                7 => array(
                    'key' => 'typeLongblob',
                    'var' => 'TypeLongblob',
                    'visibility' => 'public',
                    'value' => 'new TypeLongblob()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                8 => array(
                    'key' => 'typeTinytext',
                    'var' => 'TypeTinytext',
                    'visibility' => 'public',
                    'value' => 'new TypeTinytext()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                9 => array(
                    'key' => 'typeText',
                    'var' => 'TypeText',
                    'visibility' => 'public',
                    'value' => 'new TypeText()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                10 => array(
                    'key' => 'typeMediumtext',
                    'var' => 'TypeMediumtext',
                    'visibility' => 'public',
                    'value' => 'new TypeMediumtext()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                11 => array(
                    'key' => 'typeLongtext',
                    'var' => 'TypeLongtext',
                    'visibility' => 'public',
                    'value' => 'new TypeLongtext()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                12 => array(
                    'key' => 'typeEnum',
                    'var' => 'TypeEnum',
                    'visibility' => 'public',
                    'value' => 'new TypeEnum()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                13 => array(
                    'key' => 'typeSet',
                    'var' => 'TypeSet',
                    'visibility' => 'public',
                    'value' => 'new TypeSet()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                14 => array(
                    'key' => 'typeDate',
                    'var' => 'TypeDate',
                    'visibility' => 'public',
                    'value' => 'new TypeDate()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                15 => array(
                    'key' => 'typeTime',
                    'var' => 'TypeTime',
                    'visibility' => 'public',
                    'value' => 'new TypeTime()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                16 => array(
                    'key' => 'typeDatetime',
                    'var' => 'TypeDatetime',
                    'visibility' => 'public',
                    'value' => 'new TypeDatetime()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                17 => array(
                    'key' => 'typeTimestamp',
                    'var' => 'TypeTimestamp',
                    'visibility' => 'public',
                    'value' => 'new TypeTimestamp()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                18 => array(
                    'key' => 'typeYear',
                    'var' => 'TypeYear',
                    'visibility' => 'public',
                    'value' => 'new TypeYear()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                19 => array(
                    'key' => 'typeTinyint',
                    'var' => 'TypeTinyint',
                    'visibility' => 'public',
                    'value' => 'new TypeTinyint()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                20 => array(
                    'key' => 'typeSmallint',
                    'var' => 'TypeSmallint',
                    'visibility' => 'public',
                    'value' => 'new TypeSmallint()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                21 => array(
                    'key' => 'typeMediumint',
                    'var' => 'TypeMediumint',
                    'visibility' => 'public',
                    'value' => 'new TypeMediumint()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                22 => array(
                    'key' => 'typeInt',
                    'var' => 'TypeInt',
                    'visibility' => 'public',
                    'value' => 'new TypeInt()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                23 => array(
                    'key' => 'typeBigint',
                    'var' => 'TypeBigint',
                    'visibility' => 'public',
                    'value' => 'new TypeBigint()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                24 => array(
                    'key' => 'typeFloat',
                    'var' => 'TypeFloat',
                    'visibility' => 'public',
                    'value' => 'new TypeFloat()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                25 => array(
                    'key' => 'typeDouble',
                    'var' => 'TypeDouble',
                    'visibility' => 'public',
                    'value' => 'new TypeDouble()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                26 => array(
                    'key' => 'typeBit',
                    'var' => 'TypeBit',
                    'visibility' => 'public',
                    'value' => 'new TypeBit()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                27 => array(
                    'key' => 'typeBoolean',
                    'var' => 'TypeBoolean',
                    'visibility' => 'public',
                    'value' => 'new TypeBoolean()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                28 => array(
                    'key' => 'typeBool',
                    'var' => 'TypeBool',
                    'visibility' => 'public',
                    'value' => 'new TypeBool()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                29 => array(
                    'key' => 'typeGeometry',
                    'var' => 'TypeGeometry',
                    'visibility' => 'public',
                    'value' => 'new TypeGeometry()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                30 => array(
                    'key' => 'typePoint',
                    'var' => 'TypePoint',
                    'visibility' => 'public',
                    'value' => 'new TypePoint()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                31 => array(
                    'key' => 'typeLinestring',
                    'var' => 'TypeLinestring',
                    'visibility' => 'public',
                    'value' => 'new TypeLinestring()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                32 => array(
                    'key' => 'typePolygon',
                    'var' => 'TypePolygon',
                    'visibility' => 'public',
                    'value' => 'new TypePolygon()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                33 => array(
                    'key' => 'typeGeometrycollection',
                    'var' => 'TypeGeometrycollection',
                    'visibility' => 'public',
                    'value' => 'new TypeGeometrycollection()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                34 => array(
                    'key' => 'typeMultilinestring',
                    'var' => 'TypeMultilinestring',
                    'visibility' => 'public',
                    'value' => 'new TypeMultilinestring()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                35 => array(
                    'key' => 'typeMultipoint',
                    'var' => 'TypeMultipoint',
                    'visibility' => 'public',
                    'value' => 'new TypeMultipoint()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                36 => array(
                    'key' => 'typeMultipolygon',
                    'var' => 'TypeMultipolygon',
                    'visibility' => 'public',
                    'value' => 'new TypeMultipolygon()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
                37 => array(
                    'key' => 'typeJson',
                    'var' => 'TypeJson',
                    'visibility' => 'public',
                    'value' => 'new TypeJson()',
                    'static' => true,
                    'setter' => false,
                    'getter' => false,
                    'explicitMethodForValue' => true,
                    'listProperty' => false,
                    'createStaticPropertyGetter' => false,
                    'setValueInConstructor' => false,
                ),
            ),
            'createHelperMethods' => true,
        ),
    ),
);